<div id="welcome">
	<div id="welcome-picture">
		<div class="hintergrund1"></div>
	</div>
	<div id= "welcome-text">
		<div class="hintergrund">
		<div class="mota-user-logo">
			<img src="http://7xonju.com1.z0.glb.clouddn.com/image/logo/mainlogo.png">
		</div>
		<div class="mota-user-text">
			<p></p>
			<p></p>
			<p>爱好: 滑雪，看电影、兵乓球、听音乐、看小说</p>
			<p>微信: n1085633848</p>
		</div>
		</div>
	</div>
</div>
