<div class="readingstable"> 
	<table>
  		<tr>
    			<th>书名</th>
    			<th>类型</th>
    			<th>作者</th>
 		 </tr>
		 <tr>
    			<td><a href="/posts/36218/">李白</td>
    			<td>人工智能</td>
    			<td>金天</td>
  		</tr>
  		<tr>
    			<td><a href="/posts/56548/">人生的智慧</td>
    			<td>哲学</td>
    			<td>叔本华</td>
  		</tr>
  		<tr>
    			<td><a href="/readings">三体</td>
    			<td>硬科幻</td>
    			<td>刘慈欣</td>
  		</tr>
	</table> 
	</table> 
</div>
